services:
  - type: web
    name: sefaz-alert-slack
    env: node
    region: oregon
    plan: free
    branch: master
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: SLACK_WEBHOOK_URL
        sync: false
